// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';
import {main} from '../models';
import {chdb} from '../models';
import {profile} from '../models';
import {verify} from '../models';

export function BuildPreview(arg1:string,arg2:string):Promise<model.Preview>;

export function BuildReport(arg1:string):Promise<main.ReportOut>;

export function Busy():Promise<string>;

export function CancelE2E():Promise<void>;

export function CancelGenerate():Promise<void>;

export function DeleteProfile(arg1:string):Promise<void>;

export function DiscardE2EState():Promise<void>;

export function Discover(arg1:string):Promise<chdb.Discovery>;

export function DuplicateProfile(arg1:string):Promise<profile.Profile>;

export function E2EPreflight(arg1:string,arg2:string,arg3:boolean,arg4:boolean):Promise<main.PreflightResult>;

export function E2EReport(arg1:string):Promise<string>;

export function ExportProfiles():Promise<string>;

export function ExportProfilesFile():Promise<string>;

export function Generate(arg1:string,arg2:string,arg3:boolean,arg4:boolean):Promise<void>;

export function History(arg1:string,arg2:number,arg3:boolean):Promise<main.HistoryList>;

export function ImportProfiles(arg1:string):Promise<profile.ImportSummary>;

export function ImportProfilesFile():Promise<profile.ImportSummary>;

export function Info():Promise<main.AppInfo>;

export function ListCheckpointIDs(arg1:string,arg2:string,arg3:string,arg4:string):Promise<main.CheckpointIDs>;

export function ListCheckpoints(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number,arg6:number):Promise<main.CheckpointList>;

export function ListProfiles():Promise<Array<profile.Profile>>;

export function LoadScenarioFile():Promise<main.ScenarioFile>;

export function PendingE2E():Promise<main.PendingState>;

export function RegenChecklist(arg1:string,arg2:string):Promise<string>;

export function ReportFromHistory(arg1:string):Promise<string>;

export function RunE2E(arg1:string,arg2:string,arg3:string):Promise<void>;

export function RunVerify(arg1:string,arg2:string,arg3:boolean):Promise<verify.Result>;

export function SaveProfile(arg1:profile.Profile):Promise<profile.Profile>;

export function SaveReportFile(arg1:string,arg2:string):Promise<string>;

export function TestCH(arg1:string):Promise<main.TestResult>;

export function TestMaria(arg1:string):Promise<main.TestResult>;

export function UseProfile(arg1:string):Promise<void>;
