// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BuildPreview(arg1, arg2) {
  return window['go']['main']['App']['BuildPreview'](arg1, arg2);
}

export function BuildReport(arg1) {
  return window['go']['main']['App']['BuildReport'](arg1);
}

export function Busy() {
  return window['go']['main']['App']['Busy']();
}

export function CancelE2E() {
  return window['go']['main']['App']['CancelE2E']();
}

export function CancelGenerate() {
  return window['go']['main']['App']['CancelGenerate']();
}

export function DeleteProfile(arg1) {
  return window['go']['main']['App']['DeleteProfile'](arg1);
}

export function DiscardE2EState() {
  return window['go']['main']['App']['DiscardE2EState']();
}

export function Discover(arg1) {
  return window['go']['main']['App']['Discover'](arg1);
}

export function DuplicateProfile(arg1) {
  return window['go']['main']['App']['DuplicateProfile'](arg1);
}

export function E2EPreflight(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['E2EPreflight'](arg1, arg2, arg3, arg4);
}

export function E2EReport(arg1) {
  return window['go']['main']['App']['E2EReport'](arg1);
}

export function ExportProfiles() {
  return window['go']['main']['App']['ExportProfiles']();
}

export function ExportProfilesFile() {
  return window['go']['main']['App']['ExportProfilesFile']();
}

export function Generate(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['Generate'](arg1, arg2, arg3, arg4);
}

export function History(arg1, arg2, arg3) {
  return window['go']['main']['App']['History'](arg1, arg2, arg3);
}

export function ImportProfiles(arg1) {
  return window['go']['main']['App']['ImportProfiles'](arg1);
}

export function ImportProfilesFile() {
  return window['go']['main']['App']['ImportProfilesFile']();
}

export function Info() {
  return window['go']['main']['App']['Info']();
}

export function ListCheckpoints(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['ListCheckpoints'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function ListProfiles() {
  return window['go']['main']['App']['ListProfiles']();
}

export function LoadScenarioFile() {
  return window['go']['main']['App']['LoadScenarioFile']();
}

export function PendingE2E() {
  return window['go']['main']['App']['PendingE2E']();
}

export function RegenChecklist(arg1, arg2) {
  return window['go']['main']['App']['RegenChecklist'](arg1, arg2);
}

export function ReportFromHistory(arg1) {
  return window['go']['main']['App']['ReportFromHistory'](arg1);
}

export function RunE2E(arg1, arg2, arg3) {
  return window['go']['main']['App']['RunE2E'](arg1, arg2, arg3);
}

export function RunVerify(arg1, arg2, arg3) {
  return window['go']['main']['App']['RunVerify'](arg1, arg2, arg3);
}

export function SaveProfile(arg1) {
  return window['go']['main']['App']['SaveProfile'](arg1);
}

export function SaveReportFile(arg1, arg2) {
  return window['go']['main']['App']['SaveReportFile'](arg1, arg2);
}

export function TestCH(arg1) {
  return window['go']['main']['App']['TestCH'](arg1);
}

export function TestMaria(arg1) {
  return window['go']['main']['App']['TestMaria'](arg1);
}

export function UseProfile(arg1) {
  return window['go']['main']['App']['UseProfile'](arg1);
}
